-- MySQL Script generated by MySQL Workbench
-- Fri Jul 18 16:02:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_logicGame
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_logicGame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_logicGame` DEFAULT CHARACTER SET utf8 ;
USE `db_logicGame` ;

-- -----------------------------------------------------
-- Table `db_logicGame`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_logicGame`.`questions` (
  `qId` INT NOT NULL auto_increment,
  `content` VARCHAR(100) NOT NULL,
  `hint1` VARCHAR(100) NOT NULL,
  `hint2` VARCHAR(100) NULL,
  `hint3` VARCHAR(100) NULL,
  `answer` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`qId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_logicGame`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_logicGame`.`answers` (
  `aId` INT NOT NULL auto_increment,
  `qId` INT NOT NULL,
  `input` VARCHAR(45) NOT NULL,
  `isCorrect` TINYINT NULL,
  PRIMARY KEY (`aId`),
  CONSTRAINT `qId`
    FOREIGN KEY (`qId`)
    REFERENCES `db_logicGame`.`questions`(`qId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO questions (content, hint1, hint2, hint3, answer) VALUES
('一名男子走進一家餐廳，點了一碗海龜湯。喝了一口後，他立刻結帳離開，回家自殺了。為什麼？',
 '他以前喝過海龜湯。',
 '這次味道不一樣。',
 '他發現自己過去被騙了。',
 '他在荒島上吃的是人肉，這次才發現味道不同，崩潰自殺。'),

('女子報警說父親上吊自殺，警方一到現場就逮捕她，為什麼？',
 '她說爸爸吊在家中天花板。',
 '他們住的是公寓大樓。',
 '室內根本沒有地方綁繩子。',
 '警方推斷她是兇手，因為現場不合理。'),

('某人住在 30 樓，他每天坐電梯下樓上班，但回來時只搭到 20 樓再走樓梯，為什麼？',
 '不是故障，也不是壞習慣。',
 '這跟他有什麼生理特徵有關。',
 '他手短。',
 '他是侏儒，按不到更高的樓層。'),

('男人在沙漠中死了，旁邊有一根火柴，為什麼？',
 '他參與了一場抽籤遊戲。',
 '遊戲和火柴有關。',
 '輸的人要跳傘。',
 '飛機出了狀況，大家抽火柴決定誰跳傘，他抽到短的。'),

('一名男子在生日那天收到一盒蛋糕，吃下去後卻崩潰大哭，為什麼？',
 '他童年曾被虐待。',
 '蛋糕的味道讓他想起過去。',
 '那是他失蹤母親曾做的味道。',
 '他發現蛋糕來自失散多年的母親。'),

('一名女子開車經過紅綠燈時加速闖紅燈，卻沒被拍照罰款，為什麼？',
 '她違規了，但沒有被處罰。',
 '現場沒有攝影機。',
 '沒有電力或警察。',
 '她其實在拍電影，現場是封街。'),

('小孩走進教室後立刻大哭，老師什麼也沒說，為什麼？',
 '他看到黑板上的東西。',
 '他看見了照片。',
 '照片上是他過世的父母。',
 '學校貼出全家福做紀念，他當場情緒崩潰。'),

('男子進電梯後按了樓層卻沒有動靜，他不驚訝也不生氣，為什麼？',
 '他不是去搭電梯。',
 '那是日常的一部分。',
 '他其實是清潔人員。',
 '他在擦電梯內部，並非使用者。'),

('病人從醫院逃出，留下了一封信，內容只有「你們救了我」，為什麼？',
 '他本來想輕生。',
 '住院後改變了他的想法。',
 '但他無法承受帳單。',
 '他出院是為了逃避醫藥費。'),

('男子看到報紙頭條後開始收拾行李逃亡，為什麼？',
 '他是罪犯。',
 '新聞跟他過去的行為有關。',
 '那是他曾經犯案但沒曝光的內容。',
 '他害怕警方追查重新開始調查。');
 
 INSERT INTO questions (content, hint1, hint2, hint3, answer) VALUES
("一個男人打開收音機，聽了一會就自殺了。為什麼？",
 "他曾經遭遇過重大事件",
 "他聽到的內容與過去經歷有關",
 "他住在孤島上，之前以為全世界毀滅了",
 "他曾因空難流落荒島，多年後被救回，打開收音機才發現世界其實還存在，崩潰自殺"),

("一個人走進酒吧，問Bartender要一杯水，Bartender卻掏出槍對著他，他說謝謝就離開了。為什麼？",
 "Bartender不是想攻擊他",
 "這樣的行為解決了某個問題",
 "與身體狀況有關",
 "那人打嗝不止，Bartender嚇他止住了打嗝"),

("小明參加父親的喪禮後，第二天也死了。為什麼？",
 "死因與喪禮本身無直接關聯",
 "與父親的死因有關",
 "家裡有人想謀財害命",
 "父子倆吃了同一批被下毒的食物"),

("一個女人每天都會在上班前打電話給家裡，確認某件事。某天她沒打，當晚就報警了。為什麼？",
 "她擔心的不是人",
 "與聲音有關",
 "她家有隻金絲雀",
 "她每天都打電話確認金絲雀有叫，代表家沒失火，沒打就代表可能失火"),

("一個男人走進一間黑屋，什麼也沒做就死了。為什麼？",
 "他不是被攻擊",
 "他有責任在身",
 "這是一個工作事故",
 "他是操作飛機模擬器的人，結果真實的飛機因此墜毀，他愧疚而死"),

("一對男女在沙灘上散步，突然男人倒地不起。女人報警說他是突然死亡。為什麼警方懷疑她？",
 "他們來過這裡",
 "男人有特殊疾病",
 "女人隱瞞了某件事",
 "男人是盲人，女人之前說這是第一次來，結果男人卻說這裡跟以前一樣，女人怕謊言被拆穿"),

("一個人倒在沙灘，旁邊只有一支破傘，為什麼他會死？",
 "這與交通工具有關",
 "曾經有某種裝置",
 "與飛機相關",
 "他是從空中跳傘失敗墜地的"),

("一個小女孩總是說：“我姐姐總是在晚上唱歌給我聽。” 但她的姐姐早已去世。為什麼？",
 "與聲音有關",
 "小女孩不是在說謊",
 "與空間安排有關",
 "姐姐的錄音留存在音樂盒中，每晚自動播放") ;

