-- MySQL Script generated by MySQL Workbench
-- Fri Jul 18 16:02:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_logicGame
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_logicGame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_logicGame` DEFAULT CHARACTER SET utf8 ;
USE `db_logicGame` ;

-- -----------------------------------------------------
-- Table `db_logicGame`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_logicGame`.`questions` (
  `qId` INT NOT NULL auto_increment,
  `content` VARCHAR(45) NOT NULL,
  `hint1` VARCHAR(45) NOT NULL,
  `hint2` VARCHAR(45) NULL,
  `hint3` VARCHAR(45) NULL,
  `answer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`qId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_logicGame`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_logicGame`.`answers` (
  `aId` INT NOT NULL auto_increment,
  `qId` INT NOT NULL,
  `input` VARCHAR(45) NOT NULL,
  `isCorrect` TINYINT NULL,
  PRIMARY KEY (`aId`),
  CONSTRAINT `qId`
    FOREIGN KEY (`qId`)
    REFERENCES `db_logicGame`.`questions`
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO questions (content, hint1, hint2, hint3, answer) VALUES
('一名男子走進一家餐廳，點了一碗海龜湯。喝了一口後，他立刻結帳離開，回家自殺了。為什麼？',
 '他以前喝過海龜湯。',
 '這次味道不一樣。',
 '他發現自己過去被騙了。',
 '他在荒島上吃的是人肉，這次才發現味道不同，崩潰自殺。'),

('女子報警說父親上吊自殺，警方一到現場就逮捕她，為什麼？',
 '她說爸爸吊在家中天花板。',
 '他們住的是公寓大樓。',
 '室內根本沒有地方綁繩子。',
 '警方推斷她是兇手，因為現場不合理。'),

('某人住在 30 樓，他每天坐電梯下樓上班，但回來時只搭到 20 樓再走樓梯，為什麼？',
 '不是故障，也不是壞習慣。',
 '這跟他有什麼生理特徵有關。',
 '他手短。',
 '他是侏儒，按不到更高的樓層。'),

('男人在沙漠中死了，旁邊有一根火柴，為什麼？',
 '他參與了一場抽籤遊戲。',
 '遊戲和火柴有關。',
 '輸的人要跳傘。',
 '飛機出了狀況，大家抽火柴決定誰跳傘，他抽到短的。'),

('一名男子在生日那天收到一盒蛋糕，吃下去後卻崩潰大哭，為什麼？',
 '他童年曾被虐待。',
 '蛋糕的味道讓他想起過去。',
 '那是他失蹤母親曾做的味道。',
 '他發現蛋糕來自失散多年的母親。'),

('一名女子開車經過紅綠燈時加速闖紅燈，卻沒被拍照罰款，為什麼？',
 '她違規了，但沒有被處罰。',
 '現場沒有攝影機。',
 '沒有電力或警察。',
 '她其實在拍電影，現場是封街。'),

('小孩走進教室後立刻大哭，老師什麼也沒說，為什麼？',
 '他看到黑板上的東西。',
 '他看見了照片。',
 '照片上是他過世的父母。',
 '學校貼出全家福做紀念，他當場情緒崩潰。'),

('男子進電梯後按了樓層卻沒有動靜，他不驚訝也不生氣，為什麼？',
 '他不是去搭電梯。',
 '那是日常的一部分。',
 '他其實是清潔人員。',
 '他在擦電梯內部，並非使用者。'),

('病人從醫院逃出，留下了一封信，內容只有「你們救了我」，為什麼？',
 '他本來想輕生。',
 '住院後改變了他的想法。',
 '但他無法承受帳單。',
 '他出院是為了逃避醫藥費。'),

('男子看到報紙頭條後開始收拾行李逃亡，為什麼？',
 '他是罪犯。',
 '新聞跟他過去的行為有關。',
 '那是他曾經犯案但沒曝光的內容。',
 '他害怕警方追查重新開始調查。');
